export { default as NavBar } from "./NavBar"
export { default as Home } from "./Home"
export { default as Highlights } from "./Highlights"
export { default as Showcase } from "./Showcase"
export { default as Community } from "./Community"
export { default as Footer } from "./Footer"